services:
  not-me-fe-dc:
    image: wonseoop/not-me-fe:1.0.0 # 풀을 안받아도 도커 허브에서 가져와서 자동으로 풀
    ports:
      - "3000:3000"
    container_name: not-me-fe-dc-conatiner
    networks:
      - not-me
  not-me-be-dc:
    image : wonseoop/not-me-be:1.0.1 # 풀을 안받아도 도커 허브에서 가져와서 자동으로 풀
    ports:
      - "8080:8080"
    container_name: not-me-be-dc-container
    networks:
      - not-me
  nginx-dc:
    image : nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/projects/not-me/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-dc-container
    networks:
      - not-me

networks:
  not-me: